[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
usdv_bridge = "7SKtKQ1wMRuJ44ai68cx1tugfUPwuSHd9LTvsFJoVzXk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/seal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000  # in milliseconds (10 seconds)
